using Domain.Model.BaseModels;
using System;
using System.Collections.Generic;

namespace Domain.Model.User
{
    public class UserModel : PagedBaseModel
    {
        public long UserId { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime? LastLoginAt { get; set; }
        public DateTime LastUpdateAt { get; set; }
        public string PasswordSalt { get; set; }
        public string PasswordHash { get; set; }
        public DateTime? PasswordLastSetAt { get; set; }
        public bool PasswordIsAutogenerated { get; set; }
        public string PasswordResetToken { get; set; }
        public DateTime? PasswordResetTokenGeneratedAt { get; set; }

        public UserModel() { }
        public UserModel(string username,
                         string firstName,
                         string lastName,
                         long createdByUserId,
                         string createdByFirstName,
                         string createdByLastName,
                         string email)
        {
            Username = username;
            FirstName = firstName;
            LastName = lastName;

            CreatedAt = DateTime.Now;
            CreatedByUserId = createdByUserId;

            Email = email;
        }

        public new void Validate()
        {
            if (Username.Empty()) throw new ArgumentException("Username is not set");
            if (FirstName.Empty()) throw new ArgumentException("FirstName is not set");
            if (LastName.Empty()) throw new ArgumentException("LastName is not set");
            if (CreatedAt == DateTime.MinValue) throw new ArgumentException("CreatedAt is not set");
        }
        [IsNotTableColumn(true)]
        public string FullName => $"{string.Join(" ", new List<string> { FirstName, LastName })}";
    }
}
