USE [BudgetingApp_2_12_2022]
GO

/****** Object:  Table [dbo].[BUSINESS_TAB]    Script Date: 4/14/2022 11:48:46 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BUSINESS_TAB](
	[BusinessId] [bigint] IDENTITY(1,1) NOT NULL,
	[BusinessName] [varchar](200) NOT NULL,
	[CreatedByUserId] [bigint] NOT NULL,
	[CreatedAt] [datetime] NOT NULL,
 CONSTRAINT [PK_BUSINESS_TAB] PRIMARY KEY CLUSTERED 
(
	[BusinessId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BUSINESS_TAB]  WITH CHECK ADD  CONSTRAINT [FK_BUSINESS_TAB_USER_TAB] FOREIGN KEY([CreatedByUserId])
REFERENCES [dbo].[USER_TAB] ([UserId])
GO

ALTER TABLE [dbo].[BUSINESS_TAB] CHECK CONSTRAINT [FK_BUSINESS_TAB_USER_TAB]
GO

