USE [BudgetingApp_2_12_2022]
GO

/****** Object:  Table [dbo].[CATEGORY_TAB]    Script Date: 4/14/2022 11:48:57 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CATEGORY_TAB](
	[CategoryId] [bigint] IDENTITY(1,1) NOT NULL,
	[CategoryName] [varchar](200) NOT NULL,
	[CategoryPriority] [int] NOT NULL,
	[CreatedAt] [datetime] NOT NULL,
	[CreatedByUserId] [bigint] NOT NULL,
	[MonthlyLimit] [float] NULL,
	[WeeklyLimit] [float] NULL,
 CONSTRAINT [PK_CATEGORY_TAB] PRIMARY KEY CLUSTERED 
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [constraint_name] UNIQUE NONCLUSTERED 
(
	[CategoryName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CATEGORY_TAB]  WITH CHECK ADD  CONSTRAINT [FK_CATEGORY_TAB_ToTable] FOREIGN KEY([CreatedByUserId])
REFERENCES [dbo].[USER_TAB] ([UserId])
GO

ALTER TABLE [dbo].[CATEGORY_TAB] CHECK CONSTRAINT [FK_CATEGORY_TAB_ToTable]
GO

