USE [BudgetingApp_2_12_2022]
GO

/****** Object:  Table [dbo].[MONTHLY_PAYMENT_STATS_TAB]    Script Date: 4/14/2022 11:49:33 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MONTHLY_PAYMENT_STATS_TAB](
	[MonthlyPaymentStatsId] [bigint] IDENTITY(1,1) NOT NULL,
	[Price] [float] NOT NULL,
	[Date] [date] NOT NULL,
	[IsDeposit] [bit] NOT NULL,
	[Description] [varchar](255) NULL,
	[CreatedByUserId] [bigint] NOT NULL,
	[CreatedAt] [datetime] NOT NULL,
 CONSTRAINT [PK_MONTHLY_PAYMENT_STATS_TAB] PRIMARY KEY CLUSTERED 
(
	[MonthlyPaymentStatsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MONTHLY_PAYMENT_STATS_TAB]  WITH CHECK ADD  CONSTRAINT [FK_MONTHLY_PAYMENT_STATS_TAB_USER_TAB] FOREIGN KEY([CreatedByUserId])
REFERENCES [dbo].[USER_TAB] ([UserId])
GO

ALTER TABLE [dbo].[MONTHLY_PAYMENT_STATS_TAB] CHECK CONSTRAINT [FK_MONTHLY_PAYMENT_STATS_TAB_USER_TAB]
GO

