USE [BudgetingApp_2_12_2022]
GO

/****** Object:  Table [dbo].[PAYMENT_PRIORITY_TAB]    Script Date: 4/14/2022 11:49:45 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PAYMENT_PRIORITY_TAB](
	[PaymentPriorityId] [bigint] IDENTITY(1,1) NOT NULL,
	[PaymentPriorityName] [varchar](200) NOT NULL,
	[CreatedAt] [datetime] NOT NULL,
	[CreatedByUserId] [bigint] NOT NULL,
 CONSTRAINT [PK_PAYMENT_PRIORITY_TAB] PRIMARY KEY CLUSTERED 
(
	[PaymentPriorityId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [constraint_name2] UNIQUE NONCLUSTERED 
(
	[PaymentPriorityName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PAYMENT_PRIORITY_TAB]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENT_PRIORITY_TAB_USER_TAB] FOREIGN KEY([CreatedByUserId])
REFERENCES [dbo].[USER_TAB] ([UserId])
GO

ALTER TABLE [dbo].[PAYMENT_PRIORITY_TAB] CHECK CONSTRAINT [FK_PAYMENT_PRIORITY_TAB_USER_TAB]
GO

