USE [BudgetingApp_2_12_2022]
GO

/****** Object:  Table [dbo].[PAYMENT_TAB]    Script Date: 4/14/2022 11:49:54 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PAYMENT_TAB](
	[PaymentId] [bigint] IDENTITY(1,1) NOT NULL,
	[Title] [varchar](255) NOT NULL,
	[PaymentPriorityId] [bigint] NOT NULL,
	[BusinessId] [bigint] NOT NULL,
	[IsDeposit] [bit] NOT NULL,
	[IsPaidToPerson] [bit] NOT NULL,
	[CategoryId] [bigint] NOT NULL,
	[Price] [float] NOT NULL,
	[Date] [datetime] NOT NULL,
	[CreatedByUserId] [bigint] NOT NULL,
	[CreatedAt] [datetime] NOT NULL,
	[ApprovedAt] [datetime] NULL,
 CONSTRAINT [PK__PAYMENT___3214EC07FBE1B2BF] PRIMARY KEY CLUSTERED 
(
	[PaymentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PAYMENT_TAB] ADD  CONSTRAINT [DF_PAYMENT_TAB_PaymentPriorityId]  DEFAULT ((3)) FOR [PaymentPriorityId]
GO

ALTER TABLE [dbo].[PAYMENT_TAB]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENT_TAB_BUSINESS_TAB] FOREIGN KEY([BusinessId])
REFERENCES [dbo].[BUSINESS_TAB] ([BusinessId])
GO

ALTER TABLE [dbo].[PAYMENT_TAB] CHECK CONSTRAINT [FK_PAYMENT_TAB_BUSINESS_TAB]
GO

ALTER TABLE [dbo].[PAYMENT_TAB]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENT_TAB_CATEGORY_TAB] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[CATEGORY_TAB] ([CategoryId])
GO

ALTER TABLE [dbo].[PAYMENT_TAB] CHECK CONSTRAINT [FK_PAYMENT_TAB_CATEGORY_TAB]
GO

ALTER TABLE [dbo].[PAYMENT_TAB]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENT_TAB_PAYMENT_PRIORITY_TAB] FOREIGN KEY([PaymentPriorityId])
REFERENCES [dbo].[PAYMENT_PRIORITY_TAB] ([PaymentPriorityId])
GO

ALTER TABLE [dbo].[PAYMENT_TAB] CHECK CONSTRAINT [FK_PAYMENT_TAB_PAYMENT_PRIORITY_TAB]
GO

ALTER TABLE [dbo].[PAYMENT_TAB]  WITH CHECK ADD  CONSTRAINT [FK_PAYMNET_TAB_ToTable] FOREIGN KEY([CreatedByUserId])
REFERENCES [dbo].[USER_TAB] ([UserId])
GO

ALTER TABLE [dbo].[PAYMENT_TAB] CHECK CONSTRAINT [FK_PAYMNET_TAB_ToTable]
GO

