USE [BudgetingApp_2_12_2022]
GO

/****** Object:  Table [dbo].[PAYMENT_TOTAL_TAB]    Script Date: 4/14/2022 11:50:05 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PAYMENT_TOTAL_TAB](
	[PaymentTotalId] [bigint] IDENTITY(1,1) NOT NULL,
	[Title] [varchar](250) NOT NULL,
	[BusinessId] [bigint] NULL,
	[Price] [float] NULL,
	[Date] [datetime] NOT NULL,
	[IsDeposit] [bit] NOT NULL,
	[CreatedAt] [datetime] NOT NULL,
	[CreatedByUserId] [bigint] NOT NULL,
 CONSTRAINT [PK_PAYMENT_TOTAL_TAB] PRIMARY KEY CLUSTERED 
(
	[PaymentTotalId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PAYMENT_TOTAL_TAB]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENT_TOTAL_TAB_BUSINESS_TAB] FOREIGN KEY([BusinessId])
REFERENCES [dbo].[BUSINESS_TAB] ([BusinessId])
GO

ALTER TABLE [dbo].[PAYMENT_TOTAL_TAB] CHECK CONSTRAINT [FK_PAYMENT_TOTAL_TAB_BUSINESS_TAB]
GO

ALTER TABLE [dbo].[PAYMENT_TOTAL_TAB]  WITH CHECK ADD  CONSTRAINT [FK_PAYMENT_TOTAL_TAB_USER_TAB] FOREIGN KEY([CreatedByUserId])
REFERENCES [dbo].[USER_TAB] ([UserId])
GO

ALTER TABLE [dbo].[PAYMENT_TOTAL_TAB] CHECK CONSTRAINT [FK_PAYMENT_TOTAL_TAB_USER_TAB]
GO

