USE [BudgetingApp_2_12_2022]
GO

/****** Object:  Table [dbo].[ROLE_PERMISSION_TAB]    Script Date: 4/14/2022 11:50:16 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ROLE_PERMISSION_TAB](
	[RolePermissionId] [bigint] IDENTITY(1,1) NOT NULL,
	[PermissionType] [bigint] NOT NULL,
	[RoleId] [bigint] NOT NULL,
	[IsLocked] [bit] NOT NULL,
	[Name] [varchar](200) NOT NULL,
 CONSTRAINT [PK_ROLE_PERMISSION_TAB] PRIMARY KEY CLUSTERED 
(
	[RolePermissionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ROLE_PERMISSION_TAB]  WITH CHECK ADD  CONSTRAINT [FK_ROLE_PERMISSION_TAB_ROLE_PERMISSION_TAB] FOREIGN KEY([RoleId])
REFERENCES [dbo].[ROLE_TAB] ([RoleId])
GO

ALTER TABLE [dbo].[ROLE_PERMISSION_TAB] CHECK CONSTRAINT [FK_ROLE_PERMISSION_TAB_ROLE_PERMISSION_TAB]
GO

