USE [BudgetingApp_2_12_2022]
GO

/****** Object:  Table [dbo].[USER_TAB]    Script Date: 4/14/2022 11:50:48 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USER_TAB](
	[UserId] [bigint] IDENTITY(1,1) NOT NULL,
	[RoleId] [bigint] NOT NULL,
	[Username] [varchar](200) NOT NULL,
	[Email] [varchar](200) NOT NULL,
	[PasswordHash] [varchar](200) NOT NULL,
	[FirstName] [varchar](50) NOT NULL,
	[LastName] [varchar](50) NOT NULL,
	[UserType] [int] NOT NULL,
	[LastLogInAt] [datetime] NOT NULL,
	[PhoneNumber] [int] NOT NULL,
	[Active] [bit] NOT NULL,
	[CssFontSize] [float] NOT NULL,
	[ForcePasswordReset] [bit] NOT NULL,
	[ForceUserInformationUpdate] [bit] NOT NULL,
	[UserInitials] [varchar](200) NOT NULL,
	[PasswordLastSetAt] [datetime] NULL,
	[PasswordIsAutogenerated] [bit] NULL,
	[PasswordResetGuid] [uniqueidentifier] NULL,
 CONSTRAINT [PK_USER_TAB] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[USER_TAB]  WITH CHECK ADD  CONSTRAINT [FK_USER_TAB_ROLE_TAB] FOREIGN KEY([RoleId])
REFERENCES [dbo].[ROLE_TAB] ([RoleId])
GO

ALTER TABLE [dbo].[USER_TAB] CHECK CONSTRAINT [FK_USER_TAB_ROLE_TAB]
GO

